version: '3'

services:
  app:
    image: thecodingmachine/php:8.1-v4-apache-node16
    ports:
      - '${APP_PORT:-8080}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      PHP_EXTENSIONS: bcmath gd intl pdo_pgsql pgsql
      PHP_INI_MEMORY_LIMIT: 512M
      PHP_INI_DATE__TIMEZONE: Asia/Tokyo
      PHP_INI_MBSTRING__LANGUAGE: Japanese
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      VIRTUAL_HOST: 'mytube.local'
    volumes:
      - '.:/var/www/html'
    networks:
      - webdev

networks:
  webdev:
    external: true
    name: webdev
